### PR TITLE
feat: upgraded to use prisma 2.4.1

### PR DESCRIPTION
**Pull request by kongyujian**
Upgraded all dependencies and peer dependencies to use `"@prisma/cli": "^2.4.1"` and `"@prisma/client": "^2.4.1"`.

This upgrade will fix plenty of outstanding issues between 2.2.0 and 2.4.1.

Tests ran and all passed.

### CODE REVIEW

**Comment by Errorname** [comment]
Thank you very much for this PR! I'll merge it today and make a release soon after 👍

**Comment by BjoernRave** [comment]
I think it might make sense to also do the renames of things like: `prisma.disconnect()` to `prisma.$disconnect` in this PR

**Comment by kongyujian** [comment]
> I think it might make sense to also do the renames of things like: `prisma.disconnect()` to `prisma.$disconnect()` in this PR

Ok, in that case, I'll put up another commit for this later today. @Errorname you can sit on the deployment for a bit.

**Comment by Errorname** [comment]
Great, don't hesitate if you need help with this

**Comment by kongyujian** [comment]
Ok, probably gonna need some help. Not sure how you manage to get the packages to run nicely over here. I normally use yarn workspaces/lerna to manage my packages.

Tests are failing here on this, but I'm pretty sure they should work.

**Reason for failing:**
The bootstrap scripts install the npm remote version (2.2.0), and fail to use the locally built ones that use `$disconnect()` instead of `disconnect()`.

**Comment by kongyujian** [comment]
**Just to add further information on summary of changes:**

- Added `dotenv-cli` as root dev dependencies as one of the test was throwing an error while attempting to use a dotenv cli command (I believe you have `dotenv-cli` installed globally)
- Changed all `.disconnect` to `.$disconnect` statements

**Comment by Errorname** [comment]
Yes, there is a need to use `npm link` between the packages in order to test them all together. (See how to do it in the [Contributing Guide](https://github.com/Errorname/prisma-multi-tenant/blob/master/docs/Contributing_Guide.md#3-running-and-linking-prisma-multi-tenant)) But I agree that using Lerna or an alternative would be better. I'll make an issue to migrate this.

I removed the `$` on the disconnect method of Management since it isn't needed like Prisma, it would have created inconsistencies with the other methods.

I tested and everything works really well. Thank you for upgrading Prisma and fixing some other issues. It really helps to improve the Developer Experience for contributors 🙂

**Pull request merged**
