### PR TITLE
Fix #74/compatibility issues with prisma 2.12.0

### LINKED ISSUE #74: Comptability issues with latest prisma 2.12.0
Updating prisma to v2.12 and nexus leads me to this error

```
Error: Unknown property debug provided to PrismaClient constructor.
Read more at https://pris.ly/d/client-constructor
    at validatePrismaClientOptions (/home/ahmed/Desktop/CarRental-Backend/node_modules/.prisma-multi-tenant/management/runtime/index.js:78546:13)
    at new NewPrismaClient (/home/ahmed/Desktop/CarRental-Backend/node_modules/.prisma-multi-tenant/management/runtime/index.js:78611:9)
    at Management.<anonymous> (/home/ahmed/Desktop/CarRental-Backend/node_modules/@prisma-multi-tenant/shared/build/management.js:39:27)
    at Generator.next (<anonymous>)
    at fulfilled (/home/ahmed/Desktop/CarRental-Backend/node_modules/@prisma-multi-tenant/shared/build/management.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

### PR DESCRIPTION
**Pull request by mvhysko**
closes #74

### CODE REVIEW

**Comment by mvhysko** [comment]
@Errorname Review please this PR.

**Comment by asaadawey** [comment]
very good job

**Comment by asaadawey** [comment]
@mvhysko  don't forget to edit findOne to findUnique in find tenant method

**Comment by mvhysko** [comment]
Not valid for new Prisma version.

**Pull request closed without merging**
