### PR TITLE
:construction: Rework using Prisma2

### PR DESCRIPTION
**Pull request by Errorname**
Since Prisma2 loses support for `service/stage` and a management for multiple services, `prisma-multi-tenant` evolves to implements this support directly into the lib and a brand new CLI! 🎉 

Image of the help command from the cli:
Screenshot 2019-12-20 at 05 17 10

Example of how to use the library:
Screenshot 2019-07-29 at 13 58 08

**What's left to do ?**
- [x] Getting started guide 📝 
- [x] Complete documentation 📝 
- [ ] Examples
- [ ] Tests 🙃 
- [x] Improve UX of CLI

### CODE REVIEW

**Comment by BjoernRave** [comment]
@Errorname thanks for the work you are doing this. I would love to use this soonish in one of my applications. I am not super experienced, but if there is anything I can help you with, feel free

**Comment by Errorname** [comment]
Hi @BjoernRave ! I started this rework this summer, but since Prisma2 wasn't stable enough, I paused the rework at the time.

Since then, Prisma2 is now stable enough, so I will continue with the planned rework 🙂 I expect to find enough time to work on it sometimes around the end of the month.

If you are interested, I will need feedback with the beta version then. I'll recontact you at that time 🙂

**Comment by BjoernRave** [comment]
@Errorname that's great news. Yea I think at this point prisma2 is pretty much usable.

I would love to help with the feedback

**Comment by BjoernRave** [comment]
@Errorname sorry to bother you again, but would you say the alpha is already usable?

**Comment by Errorname** [comment]
No, this branch isn't currently usable, because it uses an old version of Prisma. A lot happened since this august, so it won't work as is.

**Pull request merged**
